// Generated by tools/native-runtime/generate.py from runtime.S. Do not edit.
namespace Hydrogen.Compiler.CodeGen.X64 {
    public class NativeRuntimeEmitter {
        public void Emit(X64Assembler code) {
            string bytes = "";
            bytes = bytes + "b80900000031ffbe00200000ba0300000041ba2200000049c7c0ffffffff4531c90f05483d01f0ffff0f83870900004989c749c747100000100049c7874810000000000001498d574031c948c7020100";
            bytes = bytes + "0000884a084883c210ffc181f90001000072e8c353415441555756525141504151415241534885ff0f882a0900004881ffffffff3f0f871d090000498b4708493b471072084889e7e850010000488b74";
            bytes = bytes + "24384881c62f1000004881e600f0ffff4989f44881fe001000007530498b47384885c07427488b0849894f384981af40100000001000004989c54889c7b90002000031c0f348ab4c89e8eb2ab8090000";
            bytes = bytes + "0031ffba0300000041ba2200000049c7c0ffffffff4531c90f05483d01f0ffff0f83a0080000498b0f4889084c896008488b4c2438488948104989074d0167084883c030415b415a41594158595a5e5f";
            bytes = bytes + "415d415c5bc348c1e80c4889c248c1ea1e4831d048b9b9e5e41c6d4758bf480fafc14889c248c1ea1b4831d048b9eb113113bb49d094480fafc14889c248c1ea1f4831d0c34889fe4881e600f0ffff48";
            bytes = bytes + "89f0e8afffffff4889c149234f204889ca48c1e20449035718488b024885c0743b4839f0740548ffc1ebdf488b4208488d50304839d77224480350104839d7731b4883781800751448c7401801000000";
            bytes = bytes + "498b57304889502849894730c353415441554989fc498b570848c1ea0bbe010000004839d6730548d1e6ebf6488d46ff4989472048c1e60449897728b80900000031ffba0300000041ba2200000049c7";
            bytes = bytes + "c0ffffffff4531c90f05483d01f0ffff0f837007000049894718498b1f4885db74474989dd4c8b43084901d84c89e8e8e2feffff4889c149234f204889ca48c1e2044903571848833a00740548ffc1eb";
            bytes = bytes + "e64c892a48895a084981c5001000004d39c572c8488b1bebb449c7473000000000498b1f4885db741548c743180000000048c7432800000000488b1bebe64d39f4730f498b3c24e8b9feffff4983c408";
            bytes = bytes + "ebec498b5f304885db7428488b4328498947304531e4488b4b104883e1f84939cc73df4a8b7c2330e888feffff4983c408ebe34d8d2749c7470800000000498b1c244885db745d48837b1800740d488b";
            bytes = bytes + "4308490147084989dcebe3488b034989042448817b08001000007528498b8740100000493b87481000007318498b473848890349895f384981874010000000100000ebaa4889df488b7308b80b000000";
            bytes = bytes + "0f05eb9a498b7f18498b7728b80b0000000f0549c7471800000000498b4708483d00000004720c4889c248c1ea024801d0eb0348d1e0483d000010007305b80000100049894710415d415c5b31c0c349";
            bytes = bytes + "8b4708c353498b5f384885db74144889df488b1bbe00100000b80b0000000f05ebe749c747380000000049c78740100000000000005bc35756525141504151415241535341544155e8b7ffffff49c787";
            bytes = bytes + "48100000000000004889e7e8cdfdffff49c7874810000000000001415d415c5b415b415a41594158595a5e5f31c0c34885ff0f84440500004889f8c34885ff0f88530500004881ffffffff070f874605";
            bytes = bytes + "000057488d3cfd08000000e8f4fbffff59488908c34885ff0f840e0500004885f60f8813050000483b370f830a050000488d44f708c35341544889fb4989f4488d7e09e8bcfbffff4c8920488d780848";
            bytes = bytes + "89de4c89e1f3a4c60700415c5bc34885ff0f84c50400004885f60f84bc04000053415441554889fb4989f44c8b2f4c032e498d7d09e87afbffff4c8928488d7808488d7308488b0bf3a4498d74240849";
            bytes = bytes + "8b0c24f3a4c60700415d415c5bc34839f774234885ff74244885f6741f488b0f483b0e75174885c9740c4883c7084883c608f3a67506b801000000c331c0c34885ff0f84440400004885f60f88490400";
            bytes = bytes + "00483b370f83400400000fb644370848c1e004498d440740c3534883ec304889f831db4885c0790848f7d8bb01000000488d74242fc6060041b80a00000031c931d249f7f080c23048ffce881648ffc1";
            bytes = bytes + "4885c075eb4885db740948ffcec6062d48ffc14889f74889cee8d8feffff4883c4305bc34883ec304889f8488d74242fc6060041b80a00000031c931d249f7f080c23048ffce881648ffc14885c075eb";
            bytes = bytes + "4889f74889cee89bfeffff4883c430c34885ff7411488d3ded030000be04000000e980feffff488d3de0030000be05000000e96ffeffff4885ff0f845c030000488b0f4883c70831c041b80100000048";
            bytes = bytes + "85c90f848a030000803f2d751349c7c0ffffffff48ffc748ffc90f84720300000fb61783ea3083fa090f8763030000486bc00a4801d041b9000000804c39c80f874d03000048ffc748ffc975d34983f8";
            bytes = bytes + "01750c483dffffff7f0f8733030000490fafc0c34885ff0f84df020000534889f3488b17488d7708bf01000000e81f0000004885db7416bf01000000488d3525030000ba01000000e8040000005b31c0";
            bytes = bytes + "c34885d2741eb8010000000f054883f8fc74ee4885c00f8ec80200004801c64829c2ebddc34885d2741b31c00f054883f8fc74f14885c00f8ea70200004801c64829c2ebe0c34885ff0f845d02000048";
            bytes = bytes + "83c70831f631d2b8020000000f054885c078104889c7b8030000000f05b801000000c331c0c34885ff0f842d02000053415441554883c70831f631d2b8020000000f054885c00f88480200004889c348";
            bytes = bytes + "89df31f6ba02000000b8080000000f054885c00f882b0200004989c44889df31f631d2b8080000000f05498d7c2409e8b0f8ffff4989c54c8920488d70084c89e24889dfe83cffffff4889dfb8030000";
            bytes = bytes + "000f0543c6442508004c89e8415d415c5bc3534154e86cffffff4889c3488b38e857fcffff31c9488b134839d1730f0fb6740b08488974c80848ffc1ebec415c5bc34885ff0f84710100004885f60f84";
            bytes = bytes + "6801000053415441554989fd4989f4e89f0000004c89ef4883c708be41020000baa4010000b8020000000f054885c00f886f0100004889c34889c7498d742408498b1424e878feffff4889dfb8030000";
            bytes = bytes + "000f054885c00f8848010000415d415c5b31c0c34885f60f84ff00000053415441554889fb4989f44c8b2e498d7d09e8c0f7ffff4c892831c94c39e9730e498b54cc088854080848ffc1ebed42c64428";
            bytes = bytes + "08004889df4889c6e845ffffff415d415c5bc34885ff0f84b000000053415441554889fb4c8b274d85e40f84d40000004883c3084531ed4d39e5733e42803c2b2f75324d85ed742d42c6042b00bf9cff";
            bytes = bytes + "ffff4889debaed010000b8020100000f0542c6042b2f4885c0740a4883f8ef0f858f00000049ffc5ebbd415d415c5b31c0c35341544155498b3e48ffcfe8fafaffff4889c34531e44c3b2373264f8b6c";
            bytes = bytes + "e61031f641807c350000740548ffc6ebf34c89efe81dfbffff4a8944e30849ffc4ebd54889d8415d415c5bc3488d356f000000ba1e000000eb44488d357f000000ba22000000eb36488d3593000000ba";
            bytes = bytes + "27000000eb28488d35ac000000ba21000000eb1a488d35bf000000ba1f000000eb0c488d35d0000000ba26000000bf02000000b8010000000f05bf01000000b83c0000000f050f0b0a7472756566616c";
            bytes = bytes + "736572756e74696d65206572726f723a206e756c6c207265666572656e63650a72756e74696d65206572726f723a20696e646578206f7574206f662072616e67650a72756e74696d65206572726f723a";
            bytes = bytes + "20696e76616c696420616c6c6f636174696f6e2073697a650a72756e74696d65206572726f723a20616c6c6f636174696f6e206661696c65640a72756e74696d65206572726f723a2066696c6520492f";
            bytes = bytes + "4f206661696c65640a72756e74696d65206572726f723a20696e76616c696420696e746567657220737472696e670a";
            int i = 0;
            while (i < bytes.Length) {
                code.EmitByte(Digit(bytes[i]) * 16 + Digit(bytes[i + 1]));
                i = i + 2;
            }
        }
        public int Offset(string name) {
            if (name == "rt_alloc") { return 100; }
            if (name == "rt_args") { return 2370; }
            if (name == "rt_array") { return 1100; }
            if (name == "rt_bool_string") { return 1536; }
            if (name == "rt_char") { return 1343; }
            if (name == "rt_check") { return 1087; }
            if (name == "rt_collect") { return 493; }
            if (name == "rt_concat") { return 1214; }
            if (name == "rt_convert_error") { return 2514; }
            if (name == "rt_create_parents") { return 2259; }
            if (name == "rt_equal") { return 1294; }
            if (name == "rt_error") { return 2526; }
            if (name == "rt_exists") { return 1830; }
            if (name == "rt_gc") { return 1015; }
            if (name == "rt_heapbytes") { return 959; }
            if (name == "rt_index") { return 1141; }
            if (name == "rt_index_error") { return 2458; }
            if (name == "rt_init") { return 0; }
            if (name == "rt_int_string") { return 1385; }
            if (name == "rt_io_error") { return 2500; }
            if (name == "rt_mark") { return 389; }
            if (name == "rt_null_error") { return 2444; }
            if (name == "rt_oom") { return 2486; }
            if (name == "rt_page_hash") { return 326; }
            if (name == "rt_print") { return 1700; }
            if (name == "rt_read_all") { return 1797; }
            if (name == "rt_read_bytes") { return 2018; }
            if (name == "rt_read_text") { return 1878; }
            if (name == "rt_release_pool") { return 964; }
            if (name == "rt_size_error") { return 2472; }
            if (name == "rt_string") { return 1174; }
            if (name == "rt_to_int") { return 1575; }
            if (name == "rt_uint_string") { return 1476; }
            if (name == "rt_write_all") { return 1761; }
            if (name == "rt_write_bytes") { return 2180; }
            if (name == "rt_write_text") { return 2066; }
            return -1;
        }
        private int Digit(string ch) {
            if (ch == "0") { return 0; }
            if (ch == "1") { return 1; }
            if (ch == "2") { return 2; }
            if (ch == "3") { return 3; }
            if (ch == "4") { return 4; }
            if (ch == "5") { return 5; }
            if (ch == "6") { return 6; }
            if (ch == "7") { return 7; }
            if (ch == "8") { return 8; }
            if (ch == "9") { return 9; }
            if (ch == "a") { return 10; }
            if (ch == "b") { return 11; }
            if (ch == "c") { return 12; }
            if (ch == "d") { return 13; }
            if (ch == "e") { return 14; }
            if (ch == "f") { return 15; }
            return 0;
        }
    }
}
