if (NOT DEFINED EXECUTE_BINARY OR NOT DEFINED INPUT_TARGET OR NOT DEFINED OUTPUT_ARTIFACT OR NOT DEFINED EXPECTED_OUTPUT_REGEX)
    message(FATAL_ERROR "EXECUTE_BINARY, INPUT_TARGET, OUTPUT_ARTIFACT, and EXPECTED_OUTPUT_REGEX are required")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT_ARTIFACT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

execute_process(
    COMMAND "${EXECUTE_BINARY}" build "${INPUT_TARGET}" -o "${OUTPUT_ARTIFACT}"
    RESULT_VARIABLE BUILD_RESULT
    OUTPUT_VARIABLE BUILD_STDOUT
    ERROR_VARIABLE BUILD_STDERR
)

set(COMBINED_OUTPUT "${BUILD_STDOUT}${BUILD_STDERR}")

if (BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR "build was expected to fail\n${COMBINED_OUTPUT}")
endif()

if (NOT COMBINED_OUTPUT MATCHES "${EXPECTED_OUTPUT_REGEX}")
    message(FATAL_ERROR "unexpected build failure output\nexpected to match: ${EXPECTED_OUTPUT_REGEX}\nactual:\n${COMBINED_OUTPUT}")
endif()
