if (NOT DEFINED EXECUTE_BINARY OR NOT DEFINED INPUT_TARGET OR NOT DEFINED EXPECTED_OUTPUT_REGEX)
    message(FATAL_ERROR "EXECUTE_BINARY, INPUT_TARGET, and EXPECTED_OUTPUT_REGEX are required")
endif()

if (NOT DEFINED RUN_ARGS)
    set(RUN_ARGS)
endif()

execute_process(
    COMMAND "${EXECUTE_BINARY}" "${INPUT_TARGET}" ${RUN_ARGS}
    RESULT_VARIABLE RUN_RESULT
    OUTPUT_VARIABLE RUN_STDOUT
    ERROR_VARIABLE RUN_STDERR
)

set(COMBINED_OUTPUT "${RUN_STDOUT}${RUN_STDERR}")

if (RUN_RESULT EQUAL 0)
    message(FATAL_ERROR "execution was expected to fail\n${COMBINED_OUTPUT}")
endif()

if (NOT COMBINED_OUTPUT MATCHES "${EXPECTED_OUTPUT_REGEX}")
    message(FATAL_ERROR "unexpected failure output\nexpected to match: ${EXPECTED_OUTPUT_REGEX}\nactual:\n${COMBINED_OUTPUT}")
endif()
