foreach(required HY_BINARY PROJECT_TARGET SOURCE_DIR TEMP_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(MAKE_DIRECTORY "${TEMP_DIR}")
set(compiler_command "${HY_BINARY}" run "${PROJECT_TARGET}" --)
if(COMPILE_CLI)
    set(NATIVE_BINARY "${TEMP_DIR}/hydrogen-compiler")
    execute_process(COMMAND "${HY_BINARY}" build "${PROJECT_TARGET}" -o "${NATIVE_BINARY}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 60)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Could not build Hydrogen CLI: ${result}\n${stdout}\n${stderr}")
    endif()
    set(compiler_command "${NATIVE_BINARY}")
elseif(DEFINED NATIVE_BINARY)
    set(compiler_command "${NATIVE_BINARY}")
endif()
set(project "${SOURCE_DIR}/tests/phase6/semantic_projects/App.hyproj")
set(INPUT_FILE "${project}")
set(OUTPUT_FILE "${TEMP_DIR}/semantic_project")
set(NATIVE_COMMAND build)
set(EXPECTED_OUTPUT "project semantics and executable IR ok\n")
set(EXPECTED_EXIT_CODE 42)
include("${SOURCE_DIR}/cmake/HyCompileNativeAndRun.cmake")
execute_process(COMMAND ${compiler_command} check "${project}" --emit-ir
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
if(NOT result STREQUAL "0" OR NOT stderr STREQUAL "")
    message(FATAL_ERROR "Project IR check failed: ${result}\n${stdout}\n${stderr}")
endif()
foreach(operation "call(Alpha.Factory.Make" "call(Beta.Factory.Make" "newobject(Alpha.Token" "newobject(Beta.Token"
    "local left : Alpha.Token" "local right : Beta.Token" "newarray(Alpha.Token" "field(" "index(" "store(" "while " "if " "return ")
    string(FIND "${stdout}" "${operation}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Executable IR does not contain '${operation}':\n${stdout}")
    endif()
endforeach()
# Each semantic failure is tested with check, compile and referenced-project build.
set(source_unknown_type "public class Program { public static int Main() { Missing value; return 0; } }")
set(reason_unknown_type "unknown type 'Missing' in Program")
set(source_unknown_name "public class Program { public static int Main() { return absent; } }")
set(reason_unknown_name "undefined name 'absent'")
set(source_scope "public class Program { public static int Main() { { int value = 1; } return value; } }")
set(reason_scope "undefined name 'value'")
set(source_argument "public class Program { public static int Main() { int value = 2; return Id(value); } public static int Id(bool flag) { return 0; } }")
set(reason_argument "argument type mismatch calling 'Id'")
set(source_unreachable "public class Program { public static int Main() { return 0; } public static int Broken() { return Missing(); } }")
set(reason_unreachable "undefined method: Program.Missing")
set(source_private_field "public class Program { public static int Main() { return new State().value; } } public class State { private int value; }")
set(reason_private_field "private field is inaccessible: State.value")
set(source_private_call "public class Program { public static int Main() { return new State().Read(); } } public class State { private int Read() { return 1; } }")
set(reason_private_call "private method is inaccessible: State.Read")
set(source_private_constructor "public class Program { public static int Main() { State state = new State(); return 0; } } public class State { private State() { } }")
set(reason_private_constructor "private constructor is inaccessible: State")
set(source_missing_field "public class Program { public static int Main() { return new State().absent; } } public class State { }")
set(reason_missing_field "undefined member 'absent' on State")
set(source_static_field "public class Program { public static int Main() { return State.value; } } public class State { public int value; }")
set(reason_static_field "field receiver does not match")
set(source_length_store "public class Program { public static int Main() { int[] values = new int[1]; values.Length = 2; return 0; } }")
set(reason_length_store "assignment target is not writable")
set(source_condition "public class Program { public static int Main() { if (1) { return 1; } return 0; } }")
set(reason_condition "condition must be bool")
set(source_return "public class Program { public static int Main() { return true; } }")
set(reason_return "return type mismatch")
set(source_break "public class Program { public static int Main() { break; return 0; } }")
set(reason_break "break or continue outside loop")
set(source_duplicate "public class Program { public static int Main() { int value = 1; int value = 2; return value; } }")
set(reason_duplicate "duplicate local or parameter 'value'")
set(source_null_var "public class Program { public static int Main() { var value = null; return 0; } }")
set(reason_null_var "var requires a value with a concrete type")
set(source_interface_new "public interface Service { int Get(); } public class Program { public static int Main() { Service value = new Service(); return 0; } }")
set(reason_interface_new "cannot instantiate an interface: Service")
set(source_no_import "public class Program { public static int Main() { Token value; return 0; } }")
set(reason_no_import "unknown type 'Token'")
set(source_ambiguous "using Alpha; using Beta; public class Program { public static int Main() { Token value; return 0; } }")
set(reason_ambiguous "ambiguous type 'Token'")
set(source_cross_type "public class Program { public static int Main() { Alpha.Token value = Beta.Factory.Make(); return 0; } }")
set(reason_cross_type "local initializer type mismatch")
foreach(case unknown_type unknown_name scope argument unreachable private_field private_call private_constructor missing_field
    static_field length_store condition return break duplicate null_var interface_new no_import ambiguous cross_type)
    set(input "${TEMP_DIR}/${case}.hy")
    file(WRITE "${input}" "${source_${case}}\n")
    set(manifest "${TEMP_DIR}/${case}.hyproj")
    # Left and Right import different namespaces, but their imports cannot leak into input.
    file(WRITE "${manifest}" "format = 2\nname = \"${case}\"\ntype = \"exe\"\nsources = [\"${input}\", \"${SOURCE_DIR}/tests/phase6/semantic_projects/Left.hy\", \"${SOURCE_DIR}/tests/phase6/semantic_projects/Right.hy\"]\nproject_references = [\"${SOURCE_DIR}/tests/phase6/semantic_projects/A.hyproj\", \"${SOURCE_DIR}/tests/phase6/semantic_projects/B.hyproj\"]\n")
    foreach(mode check compile build)
        set(path "${input}")
        if(mode STREQUAL "build" OR case MATCHES "^(ambiguous|cross_type)$")
            set(path "${manifest}")
        endif()
        # compile accepts source files; referenced type failures are covered by project check/build.
        if(mode STREQUAL "compile" AND case MATCHES "^(ambiguous|cross_type)$")
            continue()
        endif()
        set(output "${TEMP_DIR}/${case}_${mode}")
        file(WRITE "${output}" "existing artifact\n")
        set(output_args -o "${output}")
        if(mode STREQUAL "check")
            set(output_args)
        endif()
        execute_process(COMMAND ${compiler_command} "${mode}" "${path}" ${output_args}
            RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
        string(FIND "${stdout}" "${reason_${case}}" found)
        if(NOT result STREQUAL "1" OR found LESS 0 OR NOT stderr STREQUAL "")
            message(FATAL_ERROR "${mode} ${case}: expected semantic failure '${reason_${case}}', got ${result}\n${stdout}\n${stderr}")
        endif()
        file(READ "${output}" actual)
        if(NOT actual STREQUAL "existing artifact\n")
            message(FATAL_ERROR "${mode} ${case}: semantic failure overwrote artifact")
        endif()
    endforeach()
endforeach()
# Construct and mutate IR without a syntax tree. The emitted executables must change.
if(COMPILE_CLI)
    find_program(PRLIMIT_EXECUTABLE prlimit REQUIRED)
    execute_process(
        COMMAND "${PRLIMIT_EXECUTABLE}" --as=134217728 ${compiler_command} check "${PROJECT_TARGET}" --emit-ir
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 60
    )
    string(FIND "${stdout}" "func Hydrogen.Compiler.CodeGen.X64.NativeCompiler.BuildProject(string, string)" found)
    if(NOT result STREQUAL "0" OR found LESS 0 OR NOT stderr STREQUAL "")
        message(FATAL_ERROR "Compiler project closure failed semantic/IR checking: ${result}\n${stdout}\n${stderr}")
    endif()
    set(harness_project "${TEMP_DIR}/IrBackend.hyproj")
    file(WRITE "${harness_project}" "format = 2\nname = \"IrBackend\"\ntype = \"exe\"\nsources = [\"${SOURCE_DIR}/tests/phase6/native_ir_backend.hy\"]\nproject_references = [\"${SOURCE_DIR}/samples/self_hosting/Hydrogen.Compiler.CodeGen.X64/Hydrogen.Compiler.CodeGen.X64.hyproj\"]\n")
    execute_process(COMMAND "${HY_BINARY}" build "${harness_project}" -o "${TEMP_DIR}/ir_backend"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 60)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Could not build IR harness: ${result}\n${stdout}\n${stderr}")
    endif()
    execute_process(COMMAND "${TEMP_DIR}/ir_backend" "${TEMP_DIR}/ir41" "${TEMP_DIR}/ir42"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "IR harness failed: ${result}\n${stdout}\n${stderr}")
    endif()
    foreach(code 41 42)
        file(CHMOD "${TEMP_DIR}/ir${code}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
        execute_process(COMMAND "${TEMP_DIR}/ir${code}" RESULT_VARIABLE result TIMEOUT 10)
        if(NOT result STREQUAL "${code}")
            message(FATAL_ERROR "Mutated IR should return ${code}, got ${result}")
        endif()
    endforeach()
endif()
