#!/usr/bin/env python3
"""Regenerate the checked-in, position-independent native runtime byte emitter.
GNU binutils are development tools only; emitted Hydrogen executables need none.
"""
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'tools/native-runtime/runtime.S'
TARGET = ROOT / 'samples/self_hosting/Hydrogen.Compiler.CodeGen.X64/NativeRuntimeEmitter.hy'
with tempfile.TemporaryDirectory() as directory:
    obj = Path(directory) / 'runtime.o'
    binary = Path(directory) / 'runtime.bin'
    subprocess.run(['as', '--64', str(SOURCE), '-o', str(obj)], check=True)
    relocations = subprocess.check_output(['objdump', '-r', str(obj)], text=True)
    if 'R_X86_64' in relocations:
        raise RuntimeError('Runtime must contain no unresolved relocations')
    subprocess.run(['objcopy', '-O', 'binary', '-j', '.text', str(obj), str(binary)], check=True)
    data = binary.read_bytes().hex()
    symbols = subprocess.check_output(['nm', '--defined-only', str(obj)], text=True)
    offsets = {name: int(address, 16) for address, kind, name in
               (line.split() for line in symbols.splitlines()) if name.startswith('rt_')}
lines = ['// Generated by tools/native-runtime/generate.py from runtime.S. Do not edit.',
         'namespace Hydrogen.Compiler.CodeGen.X64 {', '    public class NativeRuntimeEmitter {',
         '        public void Emit(X64Assembler code) {', '            string bytes = "";']
for i in range(0, len(data), 160):
    lines.append(f'            bytes = bytes + "{data[i:i+160]}";')
lines += ['            int i = 0;', '            while (i < bytes.Length) {',
          '                code.EmitByte(Digit(bytes[i]) * 16 + Digit(bytes[i + 1]));',
          '                i = i + 2;', '            }', '        }',
          '        public int Offset(string name) {']
for name, offset in sorted(offsets.items()):
    lines.append(f'            if (name == "{name}") {{ return {offset}; }}')
lines += ['            return -1;', '        }', '        private int Digit(string ch) {']
for i, ch in enumerate('0123456789abcdef'):
    lines.append(f'            if (ch == "{ch}") {{ return {i}; }}')
lines += ['            return 0;', '        }', '    }', '}']
TARGET.write_text('\n'.join(lines) + '\n')
print(f'{len(data)//2} runtime bytes -> {TARGET.relative_to(ROOT)}')
